name: 'nightly artifacts cleanup'
on:
  schedule:
    - cron: '0 1 1/4 * *' # every 1st day of the month

jobs:
  delete-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: kolpav/purge-artifacts-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          expire-in: 3days # Setting this to 0 will delete all artifacts
